### ISSUE TITLE
Investigate Serde support

### ISSUE THREAD

**Issue by gunvirranu** [gunvirranu/block-grid#52]
Serialization support. Probably would be easy to add cause there's nothing fancy to store. Just gotta figure out the `no_std` and crate options/features stuff.

**Comment by cosmicchipsocket** [comment]
This would be useful to have for my current project. For now I will probably perform conversion to/from Vec during serialization.

**Comment by gunvirranu** [comment]
Thanks for leaving a comment, nice to see someone using this. I'm busy the next couple weeks, but I was actually planning on getting back to this soon after.
